apiVersion : apps/v1
kind : Deployment
metadata:
  name: my-web-deployment-autoscaling 
  labels:
    app : my-k8s-application
    env : prod
    owner : otimofie
spec:
  replicas : 2
  selector:
    matchLabels:
      project: test3
  template:
    metadata:
      labels:
        project: test3
    spec:
      containers:
        - name: test3-web
          image: otimofie/test
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2betav1
kind: HorizontalPodAutoscaler
metadata:
  name-my-autoscaliind
  spec:
    scaleTargetRef:
      apiVersion: apps/v2betav1
      kind: Deployment
      name: my-web-deployment-autoscaling
    minReplicas: 3
    maxReplicas: 6
    metrics:
    - type : Resource
      resource:
        name: cpu
        targetAverageUtilization: 70
    - type : Resource
      resource: 
        name : memory
        targetAverageUtilization: 80